/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YaarwinWorkingGiftCodes2026RouteImport } from './routes/yaarwin-working-gift-codes-2026'
import { Route as YaarwinGiftcodeTodayRouteImport } from './routes/yaarwin-giftcode-today'
import { Route as YaarwinBonusesRouteImport } from './routes/yaarwin-bonuses'
import { Route as YaarwinAgencyProgramRouteImport } from './routes/yaarwin-agency-program'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as GiftCodeGuideRouteImport } from './routes/gift-code-guide'
import { Route as GiftCodeRouteImport } from './routes/gift-code'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadAppRouteImport } from './routes/download-app'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const YaarwinWorkingGiftCodes2026Route =
  YaarwinWorkingGiftCodes2026RouteImport.update({
    id: '/yaarwin-working-gift-codes-2026',
    path: '/yaarwin-working-gift-codes-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const YaarwinGiftcodeTodayRoute = YaarwinGiftcodeTodayRouteImport.update({
  id: '/yaarwin-giftcode-today',
  path: '/yaarwin-giftcode-today',
  getParentRoute: () => rootRouteImport,
} as any)
const YaarwinBonusesRoute = YaarwinBonusesRouteImport.update({
  id: '/yaarwin-bonuses',
  path: '/yaarwin-bonuses',
  getParentRoute: () => rootRouteImport,
} as any)
const YaarwinAgencyProgramRoute = YaarwinAgencyProgramRouteImport.update({
  id: '/yaarwin-agency-program',
  path: '/yaarwin-agency-program',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCodeGuideRoute = GiftCodeGuideRouteImport.update({
  id: '/gift-code-guide',
  path: '/gift-code-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCodeRoute = GiftCodeRouteImport.update({
  id: '/gift-code',
  path: '/gift-code',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadAppRoute = DownloadAppRouteImport.update({
  id: '/download-app',
  path: '/download-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download-app': typeof DownloadAppRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/gift-code': typeof GiftCodeRoute
  '/gift-code-guide': typeof GiftCodeGuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/yaarwin-agency-program': typeof YaarwinAgencyProgramRoute
  '/yaarwin-bonuses': typeof YaarwinBonusesRoute
  '/yaarwin-giftcode-today': typeof YaarwinGiftcodeTodayRoute
  '/yaarwin-working-gift-codes-2026': typeof YaarwinWorkingGiftCodes2026Route
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download-app': typeof DownloadAppRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/gift-code': typeof GiftCodeRoute
  '/gift-code-guide': typeof GiftCodeGuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/yaarwin-agency-program': typeof YaarwinAgencyProgramRoute
  '/yaarwin-bonuses': typeof YaarwinBonusesRoute
  '/yaarwin-giftcode-today': typeof YaarwinGiftcodeTodayRoute
  '/yaarwin-working-gift-codes-2026': typeof YaarwinWorkingGiftCodes2026Route
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download-app': typeof DownloadAppRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/gift-code': typeof GiftCodeRoute
  '/gift-code-guide': typeof GiftCodeGuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/yaarwin-agency-program': typeof YaarwinAgencyProgramRoute
  '/yaarwin-bonuses': typeof YaarwinBonusesRoute
  '/yaarwin-giftcode-today': typeof YaarwinGiftcodeTodayRoute
  '/yaarwin-working-gift-codes-2026': typeof YaarwinWorkingGiftCodes2026Route
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/download-app'
    | '/faq'
    | '/games'
    | '/gift-code'
    | '/gift-code-guide'
    | '/how-to-play'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/yaarwin-agency-program'
    | '/yaarwin-bonuses'
    | '/yaarwin-giftcode-today'
    | '/yaarwin-working-gift-codes-2026'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/download-app'
    | '/faq'
    | '/games'
    | '/gift-code'
    | '/gift-code-guide'
    | '/how-to-play'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/yaarwin-agency-program'
    | '/yaarwin-bonuses'
    | '/yaarwin-giftcode-today'
    | '/yaarwin-working-gift-codes-2026'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/download-app'
    | '/faq'
    | '/games'
    | '/gift-code'
    | '/gift-code-guide'
    | '/how-to-play'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/yaarwin-agency-program'
    | '/yaarwin-bonuses'
    | '/yaarwin-giftcode-today'
    | '/yaarwin-working-gift-codes-2026'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DownloadAppRoute: typeof DownloadAppRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  GiftCodeRoute: typeof GiftCodeRoute
  GiftCodeGuideRoute: typeof GiftCodeGuideRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  YaarwinAgencyProgramRoute: typeof YaarwinAgencyProgramRoute
  YaarwinBonusesRoute: typeof YaarwinBonusesRoute
  YaarwinGiftcodeTodayRoute: typeof YaarwinGiftcodeTodayRoute
  YaarwinWorkingGiftCodes2026Route: typeof YaarwinWorkingGiftCodes2026Route
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaarwin-working-gift-codes-2026': {
      id: '/yaarwin-working-gift-codes-2026'
      path: '/yaarwin-working-gift-codes-2026'
      fullPath: '/yaarwin-working-gift-codes-2026'
      preLoaderRoute: typeof YaarwinWorkingGiftCodes2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-giftcode-today': {
      id: '/yaarwin-giftcode-today'
      path: '/yaarwin-giftcode-today'
      fullPath: '/yaarwin-giftcode-today'
      preLoaderRoute: typeof YaarwinGiftcodeTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-bonuses': {
      id: '/yaarwin-bonuses'
      path: '/yaarwin-bonuses'
      fullPath: '/yaarwin-bonuses'
      preLoaderRoute: typeof YaarwinBonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-agency-program': {
      id: '/yaarwin-agency-program'
      path: '/yaarwin-agency-program'
      fullPath: '/yaarwin-agency-program'
      preLoaderRoute: typeof YaarwinAgencyProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-code-guide': {
      id: '/gift-code-guide'
      path: '/gift-code-guide'
      fullPath: '/gift-code-guide'
      preLoaderRoute: typeof GiftCodeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-code': {
      id: '/gift-code'
      path: '/gift-code'
      fullPath: '/gift-code'
      preLoaderRoute: typeof GiftCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-app': {
      id: '/download-app'
      path: '/download-app'
      fullPath: '/download-app'
      preLoaderRoute: typeof DownloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  DownloadAppRoute: DownloadAppRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  GiftCodeRoute: GiftCodeRoute,
  GiftCodeGuideRoute: GiftCodeGuideRoute,
  HowToPlayRoute: HowToPlayRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  YaarwinAgencyProgramRoute: YaarwinAgencyProgramRoute,
  YaarwinBonusesRoute: YaarwinBonusesRoute,
  YaarwinGiftcodeTodayRoute: YaarwinGiftcodeTodayRoute,
  YaarwinWorkingGiftCodes2026Route: YaarwinWorkingGiftCodes2026Route,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
